name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [ published, edited ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  Deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user pipenv
          cd D:\Dolan-IncrementsInc\django-cicd
          pipenv install --deploy --ignore-pipfile

      - name: Deploy to EC2
        run: |
          cd D:\Dolan-IncrementsInc\django-cicd
          pipenv run python manage.py collectstatic --noinput
          pipenv run python manage.py migrate
          sudo systemctl restart gunicorn

#      - name: Deploy in EC2
#        env:
#          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
#          HOSTNAME: ${{ secrets.HOSTNAME  }}
#          USER_NAME: ${{ secrets.USER_NAME  }}
#
#        run: |
#          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
#          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
#
#            #Now we have got the access of EC2 and we will start the deploy .
#            cd D:\Dolan-IncrementsInc\django-cicd &&
#            git checkout main &&
#            git fetch --all &&
#            git reset --hard origin/main &&
#            git pull origin main &&
#            docker-compose -f docker-compose.prod.yml up -d --build
