name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: incrementsinc
          password: ${{ secrets.increments_password }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/Dolan001/django-cicd:main

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/django-cicd/
            docker compose pull
            docker compose up -d --build
            docker exec django-cicd python manage.py migrate
#            docker system prune -f